// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/go-gophermart/internal/jwt/decode.go

// Package jwt is a generated GoMock package.
package jwt

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDecodeConfig is a mock of DecodeConfig interface.
type MockDecodeConfig struct {
	ctrl     *gomock.Controller
	recorder *MockDecodeConfigMockRecorder
}

// MockDecodeConfigMockRecorder is the mock recorder for MockDecodeConfig.
type MockDecodeConfigMockRecorder struct {
	mock *MockDecodeConfig
}

// NewMockDecodeConfig creates a new mock instance.
func NewMockDecodeConfig(ctrl *gomock.Controller) *MockDecodeConfig {
	mock := &MockDecodeConfig{ctrl: ctrl}
	mock.recorder = &MockDecodeConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecodeConfig) EXPECT() *MockDecodeConfigMockRecorder {
	return m.recorder
}

// GetJWTSecretKey mocks base method.
func (m *MockDecodeConfig) GetJWTSecretKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWTSecretKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetJWTSecretKey indicates an expected call of GetJWTSecretKey.
func (mr *MockDecodeConfigMockRecorder) GetJWTSecretKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWTSecretKey", reflect.TypeOf((*MockDecodeConfig)(nil).GetJWTSecretKey))
}
