// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/internal/jwt/generator.go

// Package jwt is a generated GoMock package.
package jwt

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockJWTGeneratorConfigurer is a mock of JWTGeneratorConfigurer interface.
type MockJWTGeneratorConfigurer struct {
	ctrl     *gomock.Controller
	recorder *MockJWTGeneratorConfigurerMockRecorder
}

// MockJWTGeneratorConfigurerMockRecorder is the mock recorder for MockJWTGeneratorConfigurer.
type MockJWTGeneratorConfigurerMockRecorder struct {
	mock *MockJWTGeneratorConfigurer
}

// NewMockJWTGeneratorConfigurer creates a new mock instance.
func NewMockJWTGeneratorConfigurer(ctrl *gomock.Controller) *MockJWTGeneratorConfigurer {
	mock := &MockJWTGeneratorConfigurer{ctrl: ctrl}
	mock.recorder = &MockJWTGeneratorConfigurerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTGeneratorConfigurer) EXPECT() *MockJWTGeneratorConfigurerMockRecorder {
	return m.recorder
}

// GetExpireTime mocks base method.
func (m *MockJWTGeneratorConfigurer) GetExpireTime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpireTime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetExpireTime indicates an expected call of GetExpireTime.
func (mr *MockJWTGeneratorConfigurerMockRecorder) GetExpireTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpireTime", reflect.TypeOf((*MockJWTGeneratorConfigurer)(nil).GetExpireTime))
}

// GetSecretKey mocks base method.
func (m *MockJWTGeneratorConfigurer) GetSecretKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSecretKey indicates an expected call of GetSecretKey.
func (mr *MockJWTGeneratorConfigurerMockRecorder) GetSecretKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretKey", reflect.TypeOf((*MockJWTGeneratorConfigurer)(nil).GetSecretKey))
}
