// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/go-gophermart/internal/commands/accrual.go

// Package commands is a generated GoMock package.
package commands

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccrualApp is a mock of AccrualApp interface.
type MockAccrualApp struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualAppMockRecorder
}

// MockAccrualAppMockRecorder is the mock recorder for MockAccrualApp.
type MockAccrualAppMockRecorder struct {
	mock *MockAccrualApp
}

// NewMockAccrualApp creates a new mock instance.
func NewMockAccrualApp(ctrl *gomock.Controller) *MockAccrualApp {
	mock := &MockAccrualApp{ctrl: ctrl}
	mock.recorder = &MockAccrualAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualApp) EXPECT() *MockAccrualAppMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockAccrualApp) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockAccrualAppMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAccrualApp)(nil).Start), ctx)
}
