// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/go-gophermart/internal/commands/gophermart.go

// Package commands is a generated GoMock package.
package commands

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGophermartApp is a mock of GophermartApp interface.
type MockGophermartApp struct {
	ctrl     *gomock.Controller
	recorder *MockGophermartAppMockRecorder
}

// MockGophermartAppMockRecorder is the mock recorder for MockGophermartApp.
type MockGophermartAppMockRecorder struct {
	mock *MockGophermartApp
}

// NewMockGophermartApp creates a new mock instance.
func NewMockGophermartApp(ctrl *gomock.Controller) *MockGophermartApp {
	mock := &MockGophermartApp{ctrl: ctrl}
	mock.recorder = &MockGophermartAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophermartApp) EXPECT() *MockGophermartAppMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockGophermartApp) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockGophermartAppMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockGophermartApp)(nil).Start), ctx)
}
