// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/go-gophermart/pkg/server/server_configured.go

// Package server is a generated GoMock package.
package server

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockServerConfiguredAddresser is a mock of ServerConfiguredAddresser interface.
type MockServerConfiguredAddresser struct {
	ctrl     *gomock.Controller
	recorder *MockServerConfiguredAddresserMockRecorder
}

// MockServerConfiguredAddresserMockRecorder is the mock recorder for MockServerConfiguredAddresser.
type MockServerConfiguredAddresserMockRecorder struct {
	mock *MockServerConfiguredAddresser
}

// NewMockServerConfiguredAddresser creates a new mock instance.
func NewMockServerConfiguredAddresser(ctrl *gomock.Controller) *MockServerConfiguredAddresser {
	mock := &MockServerConfiguredAddresser{ctrl: ctrl}
	mock.recorder = &MockServerConfiguredAddresserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerConfiguredAddresser) EXPECT() *MockServerConfiguredAddresserMockRecorder {
	return m.recorder
}

// GetRunAddress mocks base method.
func (m *MockServerConfiguredAddresser) GetRunAddress() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunAddress")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRunAddress indicates an expected call of GetRunAddress.
func (mr *MockServerConfiguredAddresserMockRecorder) GetRunAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunAddress", reflect.TypeOf((*MockServerConfiguredAddresser)(nil).GetRunAddress))
}
