// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/go-gophermart/pkg/jwt/decoder.go

// Package jwt is a generated GoMock package.
package jwt

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJWTSecretKeyGetter is a mock of JWTSecretKeyGetter interface.
type MockJWTSecretKeyGetter struct {
	ctrl     *gomock.Controller
	recorder *MockJWTSecretKeyGetterMockRecorder
}

// MockJWTSecretKeyGetterMockRecorder is the mock recorder for MockJWTSecretKeyGetter.
type MockJWTSecretKeyGetterMockRecorder struct {
	mock *MockJWTSecretKeyGetter
}

// NewMockJWTSecretKeyGetter creates a new mock instance.
func NewMockJWTSecretKeyGetter(ctrl *gomock.Controller) *MockJWTSecretKeyGetter {
	mock := &MockJWTSecretKeyGetter{ctrl: ctrl}
	mock.recorder = &MockJWTSecretKeyGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTSecretKeyGetter) EXPECT() *MockJWTSecretKeyGetterMockRecorder {
	return m.recorder
}

// GetSecretKey mocks base method.
func (m *MockJWTSecretKeyGetter) GetSecretKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSecretKey indicates an expected call of GetSecretKey.
func (mr *MockJWTSecretKeyGetterMockRecorder) GetSecretKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretKey", reflect.TypeOf((*MockJWTSecretKeyGetter)(nil).GetSecretKey))
}
