// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/internal/repositories/order_save.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderExecutor is a mock of OrderExecutor interface.
type MockOrderExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockOrderExecutorMockRecorder
}

// MockOrderExecutorMockRecorder is the mock recorder for MockOrderExecutor.
type MockOrderExecutorMockRecorder struct {
	mock *MockOrderExecutor
}

// NewMockOrderExecutor creates a new mock instance.
func NewMockOrderExecutor(ctrl *gomock.Controller) *MockOrderExecutor {
	mock := &MockOrderExecutor{ctrl: ctrl}
	mock.recorder = &MockOrderExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderExecutor) EXPECT() *MockOrderExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockOrderExecutor) Execute(ctx context.Context, query string, argMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, query, argMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockOrderExecutorMockRecorder) Execute(ctx, query, argMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockOrderExecutor)(nil).Execute), ctx, query, argMap)
}
