// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/internal/repositories/order_exists.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderExistsQuerier is a mock of OrderExistsQuerier interface.
type MockOrderExistsQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockOrderExistsQuerierMockRecorder
}

// MockOrderExistsQuerierMockRecorder is the mock recorder for MockOrderExistsQuerier.
type MockOrderExistsQuerierMockRecorder struct {
	mock *MockOrderExistsQuerier
}

// NewMockOrderExistsQuerier creates a new mock instance.
func NewMockOrderExistsQuerier(ctrl *gomock.Controller) *MockOrderExistsQuerier {
	mock := &MockOrderExistsQuerier{ctrl: ctrl}
	mock.recorder = &MockOrderExistsQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderExistsQuerier) EXPECT() *MockOrderExistsQuerierMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockOrderExistsQuerier) Query(ctx context.Context, dest any, query string, argMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, dest, query, argMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MockOrderExistsQuerierMockRecorder) Query(ctx, dest, query, argMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockOrderExistsQuerier)(nil).Query), ctx, dest, query, argMap)
}
