// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/internal/repositories/order_get_by_id.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderGetByIDQuerier is a mock of OrderGetByIDQuerier interface.
type MockOrderGetByIDQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockOrderGetByIDQuerierMockRecorder
}

// MockOrderGetByIDQuerierMockRecorder is the mock recorder for MockOrderGetByIDQuerier.
type MockOrderGetByIDQuerierMockRecorder struct {
	mock *MockOrderGetByIDQuerier
}

// NewMockOrderGetByIDQuerier creates a new mock instance.
func NewMockOrderGetByIDQuerier(ctrl *gomock.Controller) *MockOrderGetByIDQuerier {
	mock := &MockOrderGetByIDQuerier{ctrl: ctrl}
	mock.recorder = &MockOrderGetByIDQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderGetByIDQuerier) EXPECT() *MockOrderGetByIDQuerierMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockOrderGetByIDQuerier) Query(ctx context.Context, dest any, query string, argMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, dest, query, argMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MockOrderGetByIDQuerierMockRecorder) Query(ctx, dest, query, argMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockOrderGetByIDQuerier)(nil).Query), ctx, dest, query, argMap)
}
