// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/internal/repositories/reward_save.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRewardExecutor is a mock of RewardExecutor interface.
type MockRewardExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockRewardExecutorMockRecorder
}

// MockRewardExecutorMockRecorder is the mock recorder for MockRewardExecutor.
type MockRewardExecutorMockRecorder struct {
	mock *MockRewardExecutor
}

// NewMockRewardExecutor creates a new mock instance.
func NewMockRewardExecutor(ctrl *gomock.Controller) *MockRewardExecutor {
	mock := &MockRewardExecutor{ctrl: ctrl}
	mock.recorder = &MockRewardExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardExecutor) EXPECT() *MockRewardExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRewardExecutor) Execute(ctx context.Context, query string, argMap map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, query, argMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockRewardExecutorMockRecorder) Execute(ctx, query, argMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRewardExecutor)(nil).Execute), ctx, query, argMap)
}
