// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/internal/repositories/reward_exists.go

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRewardExistsQuerier is a mock of RewardExistsQuerier interface.
type MockRewardExistsQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockRewardExistsQuerierMockRecorder
}

// MockRewardExistsQuerierMockRecorder is the mock recorder for MockRewardExistsQuerier.
type MockRewardExistsQuerierMockRecorder struct {
	mock *MockRewardExistsQuerier
}

// NewMockRewardExistsQuerier creates a new mock instance.
func NewMockRewardExistsQuerier(ctrl *gomock.Controller) *MockRewardExistsQuerier {
	mock := &MockRewardExistsQuerier{ctrl: ctrl}
	mock.recorder = &MockRewardExistsQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardExistsQuerier) EXPECT() *MockRewardExistsQuerierMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockRewardExistsQuerier) Query(ctx context.Context, dest any, query string, args map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, dest, query, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MockRewardExistsQuerierMockRecorder) Query(ctx, dest, query, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockRewardExistsQuerier)(nil).Query), ctx, dest, query, args)
}
