// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/go-gophermart/internal/middlewares/auth.go

// Package middlewares is a generated GoMock package.
package middlewares

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJWTConfig is a mock of JWTConfig interface.
type MockJWTConfig struct {
	ctrl     *gomock.Controller
	recorder *MockJWTConfigMockRecorder
}

// MockJWTConfigMockRecorder is the mock recorder for MockJWTConfig.
type MockJWTConfigMockRecorder struct {
	mock *MockJWTConfig
}

// NewMockJWTConfig creates a new mock instance.
func NewMockJWTConfig(ctrl *gomock.Controller) *MockJWTConfig {
	mock := &MockJWTConfig{ctrl: ctrl}
	mock.recorder = &MockJWTConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTConfig) EXPECT() *MockJWTConfigMockRecorder {
	return m.recorder
}

// GetJWTSecretKey mocks base method.
func (m *MockJWTConfig) GetJWTSecretKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWTSecretKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetJWTSecretKey indicates an expected call of GetJWTSecretKey.
func (mr *MockJWTConfigMockRecorder) GetJWTSecretKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWTSecretKey", reflect.TypeOf((*MockJWTConfig)(nil).GetJWTSecretKey))
}

// MockClaims is a mock of Claims interface.
type MockClaims struct {
	ctrl     *gomock.Controller
	recorder *MockClaimsMockRecorder
}

// MockClaimsMockRecorder is the mock recorder for MockClaims.
type MockClaimsMockRecorder struct {
	mock *MockClaims
}

// NewMockClaims creates a new mock instance.
func NewMockClaims(ctrl *gomock.Controller) *MockClaims {
	mock := &MockClaims{ctrl: ctrl}
	mock.recorder = &MockClaimsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClaims) EXPECT() *MockClaimsMockRecorder {
	return m.recorder
}

// GetLogin mocks base method.
func (m *MockClaims) GetLogin() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogin")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLogin indicates an expected call of GetLogin.
func (mr *MockClaimsMockRecorder) GetLogin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogin", reflect.TypeOf((*MockClaims)(nil).GetLogin))
}
