// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/go-gophermart/internal/middlewares/auth.go

// Package middlewares is a generated GoMock package.
package middlewares

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sbilibin2017/go-gophermart/internal/types"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id *types.UserID) (*types.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*types.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// MockJWTDecoder is a mock of JWTDecoder interface.
type MockJWTDecoder struct {
	ctrl     *gomock.Controller
	recorder *MockJWTDecoderMockRecorder
}

// MockJWTDecoderMockRecorder is the mock recorder for MockJWTDecoder.
type MockJWTDecoderMockRecorder struct {
	mock *MockJWTDecoder
}

// NewMockJWTDecoder creates a new mock instance.
func NewMockJWTDecoder(ctrl *gomock.Controller) *MockJWTDecoder {
	mock := &MockJWTDecoder{ctrl: ctrl}
	mock.recorder = &MockJWTDecoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTDecoder) EXPECT() *MockJWTDecoderMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockJWTDecoder) Decode(tokenString string) (*types.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", tokenString)
	ret0, _ := ret[0].(*types.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decode indicates an expected call of Decode.
func (mr *MockJWTDecoderMockRecorder) Decode(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockJWTDecoder)(nil).Decode), tokenString)
}
