// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-gophermart/internal/jwt/generator.go

// Package jwt is a generated GoMock package.
package jwt

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockJWTGeneratorConfigurer is a mock of JWTGeneratorConfigurer interface.
type MockJWTGeneratorConfigurer struct {
	ctrl     *gomock.Controller
	recorder *MockJWTGeneratorConfigurerMockRecorder
}

// MockJWTGeneratorConfigurerMockRecorder is the mock recorder for MockJWTGeneratorConfigurer.
type MockJWTGeneratorConfigurerMockRecorder struct {
	mock *MockJWTGeneratorConfigurer
}

// NewMockJWTGeneratorConfigurer creates a new mock instance.
func NewMockJWTGeneratorConfigurer(ctrl *gomock.Controller) *MockJWTGeneratorConfigurer {
	mock := &MockJWTGeneratorConfigurer{ctrl: ctrl}
	mock.recorder = &MockJWTGeneratorConfigurerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTGeneratorConfigurer) EXPECT() *MockJWTGeneratorConfigurerMockRecorder {
	return m.recorder
}

// GetJWTExpireTime mocks base method.
func (m *MockJWTGeneratorConfigurer) GetJWTExpireTime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWTExpireTime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetJWTExpireTime indicates an expected call of GetJWTExpireTime.
func (mr *MockJWTGeneratorConfigurerMockRecorder) GetJWTExpireTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWTExpireTime", reflect.TypeOf((*MockJWTGeneratorConfigurer)(nil).GetJWTExpireTime))
}

// GetJWTSecretKey mocks base method.
func (m *MockJWTGeneratorConfigurer) GetJWTSecretKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWTSecretKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetJWTSecretKey indicates an expected call of GetJWTSecretKey.
func (mr *MockJWTGeneratorConfigurerMockRecorder) GetJWTSecretKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWTSecretKey", reflect.TypeOf((*MockJWTGeneratorConfigurer)(nil).GetJWTSecretKey))
}
