package constants

const (
	GOPHERMART_ORDER_STATUS_NEW        = "NEW"
	GOPHERMART_ORDER_STATUS_PROCESSING = "PROCESSING"
	GOPHERMART_ORDER_STATUS_INVALID    = "INVALID"
	GOPHERMART_ORDER_STATUS_PROCESSED  = "PROCESSED"
)
